// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Metric struct {
	ID                uuid.UUID
	TotalFileSize     int64
	TotalFileCount    int64
	FilesByMimetype   []byte
	LargestFileSize   int64
	SmallestFileSize  int64
	AverageFileSize   pgtype.Numeric
	TotalDeletedFiles int64
	LastUpdated       pgtype.Timestamp
}

type Session struct {
	ID           pgtype.UUID
	FileSize     int64
	ChunkSize    int64
	MaxChunk     int64
	FileName     pgtype.Text
	TempPath     pgtype.Text
	OwnerID      pgtype.Text
	CurrentChunk pgtype.Int8
	Provider     pgtype.Text
	CreatedAt    pgtype.Timestamp
}

type UploadedFile struct {
	ID               uuid.UUID
	FileName         string
	FilePath         string
	FileSize         int64
	FileType         pgtype.Text
	UploadedBy       string
	UploadedAt       pgtype.Timestamp
	IsDeleted        pgtype.Bool
	Checksum         pgtype.Text
	Description      pgtype.Text
	Provider         string
	ProviderMetadata []byte
}

type User struct {
	ID        pgtype.UUID
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
	LastLogin pgtype.Timestamp
}
