// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const averageChunkSize = `-- name: AverageChunkSize :one
SELECT AVG(chunk_size) AS average_chunk_size FROM sessions
`

func (q *Queries) AverageChunkSize(ctx context.Context) (float64, error) {
	row := q.db.QueryRow(ctx, averageChunkSize)
	var average_chunk_size float64
	err := row.Scan(&average_chunk_size)
	return average_chunk_size, err
}

const countSessions = `-- name: CountSessions :one
SELECT COUNT(*) AS total_sessions FROM sessions
`

func (q *Queries) CountSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSessions)
	var total_sessions int64
	err := row.Scan(&total_sessions)
	return total_sessions, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (file_size, chunk_size, max_chunk, file_name, temp_path, owner_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, file_size, chunk_size, max_chunk, file_name, temp_path, owner_id, current_chunk, created_at
`

type CreateSessionParams struct {
	FileSize  int64
	ChunkSize int64
	MaxChunk  int64
	FileName  pgtype.Text
	TempPath  pgtype.Text
	OwnerID   pgtype.Text
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.FileSize,
		arg.ChunkSize,
		arg.MaxChunk,
		arg.FileName,
		arg.TempPath,
		arg.OwnerID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.FileSize,
		&i.ChunkSize,
		&i.MaxChunk,
		&i.FileName,
		&i.TempPath,
		&i.OwnerID,
		&i.CurrentChunk,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const findDuplicateFileNames = `-- name: FindDuplicateFileNames :many
SELECT file_name, COUNT(*) AS duplicate_count
FROM sessions
GROUP BY file_name
HAVING COUNT(*) > 1
`

type FindDuplicateFileNamesRow struct {
	FileName       pgtype.Text
	DuplicateCount int64
}

func (q *Queries) FindDuplicateFileNames(ctx context.Context) ([]FindDuplicateFileNamesRow, error) {
	rows, err := q.db.Query(ctx, findDuplicateFileNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindDuplicateFileNamesRow
	for rows.Next() {
		var i FindDuplicateFileNamesRow
		if err := rows.Scan(&i.FileName, &i.DuplicateCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findLargeSessions = `-- name: FindLargeSessions :many
SELECT id, file_size, chunk_size, max_chunk, file_name, temp_path, owner_id, current_chunk, created_at FROM sessions
WHERE file_size > $1
`

func (q *Queries) FindLargeSessions(ctx context.Context, fileSize int64) ([]Session, error) {
	rows, err := q.db.Query(ctx, findLargeSessions, fileSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.FileSize,
			&i.ChunkSize,
			&i.MaxChunk,
			&i.FileName,
			&i.TempPath,
			&i.OwnerID,
			&i.CurrentChunk,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findMissingTempPaths = `-- name: FindMissingTempPaths :many
SELECT id, file_size, chunk_size, max_chunk, file_name, temp_path, owner_id, current_chunk, created_at FROM sessions
WHERE temp_path IS NULL OR temp_path = ''
`

func (q *Queries) FindMissingTempPaths(ctx context.Context) ([]Session, error) {
	rows, err := q.db.Query(ctx, findMissingTempPaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.FileSize,
			&i.ChunkSize,
			&i.MaxChunk,
			&i.FileName,
			&i.TempPath,
			&i.OwnerID,
			&i.CurrentChunk,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSessionById = `-- name: FindSessionById :one
SELECT id, file_size, chunk_size, max_chunk, file_name, temp_path, owner_id, current_chunk, created_at FROM sessions
WHERE id = $1
`

func (q *Queries) FindSessionById(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, findSessionById, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.FileSize,
		&i.ChunkSize,
		&i.MaxChunk,
		&i.FileName,
		&i.TempPath,
		&i.OwnerID,
		&i.CurrentChunk,
		&i.CreatedAt,
	)
	return i, err
}

const findSessionsAfterDate = `-- name: FindSessionsAfterDate :many
SELECT id, file_size, chunk_size, max_chunk, file_name, temp_path, owner_id, current_chunk, created_at FROM sessions
WHERE created_at > $1
`

func (q *Queries) FindSessionsAfterDate(ctx context.Context, createdAt pgtype.Timestamp) ([]Session, error) {
	rows, err := q.db.Query(ctx, findSessionsAfterDate, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.FileSize,
			&i.ChunkSize,
			&i.MaxChunk,
			&i.FileName,
			&i.TempPath,
			&i.OwnerID,
			&i.CurrentChunk,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSessionsByDate = `-- name: FindSessionsByDate :many

SELECT id, file_size, chunk_size, max_chunk, file_name, temp_path, owner_id, current_chunk, created_at FROM sessions
WHERE DATE(created_at) = $1
`

// Requires using a slice/array in Go
func (q *Queries) FindSessionsByDate(ctx context.Context, createdAt pgtype.Timestamp) ([]Session, error) {
	rows, err := q.db.Query(ctx, findSessionsByDate, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.FileSize,
			&i.ChunkSize,
			&i.MaxChunk,
			&i.FileName,
			&i.TempPath,
			&i.OwnerID,
			&i.CurrentChunk,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSessionsByOwner = `-- name: FindSessionsByOwner :many
SELECT id, file_size, chunk_size, max_chunk, file_name, temp_path, owner_id, current_chunk, created_at FROM sessions
WHERE owner_id = $1
`

func (q *Queries) FindSessionsByOwner(ctx context.Context, ownerID pgtype.Text) ([]Session, error) {
	rows, err := q.db.Query(ctx, findSessionsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.FileSize,
			&i.ChunkSize,
			&i.MaxChunk,
			&i.FileName,
			&i.TempPath,
			&i.OwnerID,
			&i.CurrentChunk,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSessionsByOwnerIndexed = `-- name: FindSessionsByOwnerIndexed :many
SELECT id, file_size, chunk_size, max_chunk, file_name, temp_path, owner_id, current_chunk, created_at FROM sessions
WHERE owner_id = $1
`

func (q *Queries) FindSessionsByOwnerIndexed(ctx context.Context, ownerID pgtype.Text) ([]Session, error) {
	rows, err := q.db.Query(ctx, findSessionsByOwnerIndexed, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.FileSize,
			&i.ChunkSize,
			&i.MaxChunk,
			&i.FileName,
			&i.TempPath,
			&i.OwnerID,
			&i.CurrentChunk,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSessionsByOwners = `-- name: FindSessionsByOwners :many
SELECT id, file_size, chunk_size, max_chunk, file_name, temp_path, owner_id, current_chunk, created_at FROM sessions
WHERE owner_id IN ($1)
`

func (q *Queries) FindSessionsByOwners(ctx context.Context, ownerID pgtype.Text) ([]Session, error) {
	rows, err := q.db.Query(ctx, findSessionsByOwners, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.FileSize,
			&i.ChunkSize,
			&i.MaxChunk,
			&i.FileName,
			&i.TempPath,
			&i.OwnerID,
			&i.CurrentChunk,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionDetails = `-- name: ListSessionDetails :many
SELECT id, file_name, owner_id, created_at FROM sessions
`

type ListSessionDetailsRow struct {
	ID        pgtype.UUID
	FileName  pgtype.Text
	OwnerID   pgtype.Text
	CreatedAt pgtype.Timestamp
}

func (q *Queries) ListSessionDetails(ctx context.Context) ([]ListSessionDetailsRow, error) {
	rows, err := q.db.Query(ctx, listSessionDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionDetailsRow
	for rows.Next() {
		var i ListSessionDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, file_size, chunk_size, max_chunk, file_name, temp_path, owner_id, current_chunk, created_at FROM sessions
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.FileSize,
			&i.ChunkSize,
			&i.MaxChunk,
			&i.FileName,
			&i.TempPath,
			&i.OwnerID,
			&i.CurrentChunk,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const paginateSessions = `-- name: PaginateSessions :many
SELECT id, file_size, chunk_size, max_chunk, file_name, temp_path, owner_id, current_chunk, created_at FROM sessions
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type PaginateSessionsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) PaginateSessions(ctx context.Context, arg PaginateSessionsParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, paginateSessions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.FileSize,
			&i.ChunkSize,
			&i.MaxChunk,
			&i.FileName,
			&i.TempPath,
			&i.OwnerID,
			&i.CurrentChunk,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalFileSize = `-- name: TotalFileSize :one
SELECT SUM(file_size) AS total_file_size FROM sessions
`

func (q *Queries) TotalFileSize(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, totalFileSize)
	var total_file_size int64
	err := row.Scan(&total_file_size)
	return total_file_size, err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE sessions
SET file_name = $1, temp_path = $2, current_chunk = $3
WHERE id = $4
`

type UpdateSessionParams struct {
	FileName     pgtype.Text
	TempPath     pgtype.Text
	CurrentChunk pgtype.Int8
	ID           pgtype.UUID
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.Exec(ctx, updateSession,
		arg.FileName,
		arg.TempPath,
		arg.CurrentChunk,
		arg.ID,
	)
	return err
}
