// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const averageChunkSize = `-- name: AverageChunkSize :one
SELECT AVG(chunk_size) AS average_chunk_size FROM sessions
`

func (q *Queries) AverageChunkSize(ctx context.Context) (float64, error) {
	row := q.db.QueryRow(ctx, averageChunkSize)
	var average_chunk_size float64
	err := row.Scan(&average_chunk_size)
	return average_chunk_size, err
}

const checkEmailExists = `-- name: CheckEmailExists :one
SELECT EXISTS (
    SELECT 1 FROM users WHERE email = $1
) AS email_exists
`

func (q *Queries) CheckEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, checkEmailExists, email)
	var email_exists bool
	err := row.Scan(&email_exists)
	return email_exists, err
}

const countFilesByUser = `-- name: CountFilesByUser :one
SELECT COUNT(*) AS user_file_count
FROM uploaded_files
WHERE uploaded_by = $1
`

func (q *Queries) CountFilesByUser(ctx context.Context, uploadedBy string) (int64, error) {
	row := q.db.QueryRow(ctx, countFilesByUser, uploadedBy)
	var user_file_count int64
	err := row.Scan(&user_file_count)
	return user_file_count, err
}

const countSessions = `-- name: CountSessions :one
SELECT COUNT(*) AS total_sessions FROM sessions
`

func (q *Queries) CountSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSessions)
	var total_sessions int64
	err := row.Scan(&total_sessions)
	return total_sessions, err
}

const countTotalFiles = `-- name: CountTotalFiles :one
SELECT COUNT(*) AS total_files FROM uploaded_files
`

func (q *Queries) CountTotalFiles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTotalFiles)
	var total_files int64
	err := row.Scan(&total_files)
	return total_files, err
}

const countTotalUsers = `-- name: CountTotalUsers :one
SELECT COUNT(*) AS total_users FROM users
`

func (q *Queries) CountTotalUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTotalUsers)
	var total_users int64
	err := row.Scan(&total_users)
	return total_users, err
}

const countUsersAfterDate = `-- name: CountUsersAfterDate :one
SELECT COUNT(*) AS recent_users
FROM users
WHERE created_at > $1
`

func (q *Queries) CountUsersAfterDate(ctx context.Context, createdAt pgtype.Timestamp) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersAfterDate, createdAt)
	var recent_users int64
	err := row.Scan(&recent_users)
	return recent_users, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (file_size, chunk_size, max_chunk, file_name, temp_path, owner_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, file_size, chunk_size, max_chunk, file_name, temp_path, owner_id, current_chunk, created_at
`

type CreateSessionParams struct {
	FileSize  int64
	ChunkSize int64
	MaxChunk  int64
	FileName  pgtype.Text
	TempPath  pgtype.Text
	OwnerID   pgtype.Text
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.FileSize,
		arg.ChunkSize,
		arg.MaxChunk,
		arg.FileName,
		arg.TempPath,
		arg.OwnerID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.FileSize,
		&i.ChunkSize,
		&i.MaxChunk,
		&i.FileName,
		&i.TempPath,
		&i.OwnerID,
		&i.CurrentChunk,
		&i.CreatedAt,
	)
	return i, err
}

const createUploadedFile = `-- name: CreateUploadedFile :one
INSERT INTO uploaded_files (
    file_name, file_path, file_size, file_type, uploaded_by, checksum, description, provider, provider_metadata
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, file_name, file_path, file_size, file_type, uploaded_by, uploaded_at, is_deleted, checksum, description, provider, provider_metadata
`

type CreateUploadedFileParams struct {
	FileName         string
	FilePath         string
	FileSize         int64
	FileType         pgtype.Text
	UploadedBy       string
	Checksum         pgtype.Text
	Description      pgtype.Text
	Provider         string
	ProviderMetadata []byte
}

func (q *Queries) CreateUploadedFile(ctx context.Context, arg CreateUploadedFileParams) (UploadedFile, error) {
	row := q.db.QueryRow(ctx, createUploadedFile,
		arg.FileName,
		arg.FilePath,
		arg.FileSize,
		arg.FileType,
		arg.UploadedBy,
		arg.Checksum,
		arg.Description,
		arg.Provider,
		arg.ProviderMetadata,
	)
	var i UploadedFile
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.FileType,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.IsDeleted,
		&i.Checksum,
		&i.Description,
		&i.Provider,
		&i.ProviderMetadata,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password)
VALUES ($1, $2)
RETURNING id, email, password, created_at, last_login
`

type CreateUserParams struct {
	Email    string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserByID, id)
	return err
}

const findDuplicateFileNames = `-- name: FindDuplicateFileNames :many
SELECT file_name, COUNT(*) AS duplicate_count
FROM sessions
GROUP BY file_name
HAVING COUNT(*) > 1
`

type FindDuplicateFileNamesRow struct {
	FileName       pgtype.Text
	DuplicateCount int64
}

func (q *Queries) FindDuplicateFileNames(ctx context.Context) ([]FindDuplicateFileNamesRow, error) {
	rows, err := q.db.Query(ctx, findDuplicateFileNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindDuplicateFileNamesRow
	for rows.Next() {
		var i FindDuplicateFileNamesRow
		if err := rows.Scan(&i.FileName, &i.DuplicateCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findDuplicateFilesByChecksum = `-- name: FindDuplicateFilesByChecksum :many
SELECT checksum, COUNT(*) AS duplicate_count
FROM uploaded_files
GROUP BY checksum
HAVING COUNT(*) > 1
`

type FindDuplicateFilesByChecksumRow struct {
	Checksum       pgtype.Text
	DuplicateCount int64
}

func (q *Queries) FindDuplicateFilesByChecksum(ctx context.Context) ([]FindDuplicateFilesByChecksumRow, error) {
	rows, err := q.db.Query(ctx, findDuplicateFilesByChecksum)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindDuplicateFilesByChecksumRow
	for rows.Next() {
		var i FindDuplicateFilesByChecksumRow
		if err := rows.Scan(&i.Checksum, &i.DuplicateCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findFilesAfterDate = `-- name: FindFilesAfterDate :many
SELECT id, file_name, file_path, file_size, file_type, uploaded_by, uploaded_at, is_deleted, checksum, description, provider, provider_metadata FROM uploaded_files
WHERE uploaded_at > $1
`

func (q *Queries) FindFilesAfterDate(ctx context.Context, uploadedAt pgtype.Timestamp) ([]UploadedFile, error) {
	rows, err := q.db.Query(ctx, findFilesAfterDate, uploadedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadedFile
	for rows.Next() {
		var i UploadedFile
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.FileType,
			&i.UploadedBy,
			&i.UploadedAt,
			&i.IsDeleted,
			&i.Checksum,
			&i.Description,
			&i.Provider,
			&i.ProviderMetadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findFilesByMetadataKey = `-- name: FindFilesByMetadataKey :many
SELECT id, file_name, file_path, file_size, file_type, uploaded_by, uploaded_at, is_deleted, checksum, description, provider, provider_metadata FROM uploaded_files
WHERE provider_metadata ? $1
`

func (q *Queries) FindFilesByMetadataKey(ctx context.Context, providerMetadata []byte) ([]UploadedFile, error) {
	rows, err := q.db.Query(ctx, findFilesByMetadataKey, providerMetadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadedFile
	for rows.Next() {
		var i UploadedFile
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.FileType,
			&i.UploadedBy,
			&i.UploadedAt,
			&i.IsDeleted,
			&i.Checksum,
			&i.Description,
			&i.Provider,
			&i.ProviderMetadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findFilesByProvider = `-- name: FindFilesByProvider :many
SELECT id, file_name, file_path, file_size, file_type, uploaded_by, uploaded_at, is_deleted, checksum, description, provider, provider_metadata FROM uploaded_files
WHERE provider = $1
`

func (q *Queries) FindFilesByProvider(ctx context.Context, provider string) ([]UploadedFile, error) {
	rows, err := q.db.Query(ctx, findFilesByProvider, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadedFile
	for rows.Next() {
		var i UploadedFile
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.FileType,
			&i.UploadedBy,
			&i.UploadedAt,
			&i.IsDeleted,
			&i.Checksum,
			&i.Description,
			&i.Provider,
			&i.ProviderMetadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findFilesByUser = `-- name: FindFilesByUser :many
SELECT id, file_name, file_path, file_size, file_type, uploaded_by, uploaded_at, is_deleted, checksum, description, provider, provider_metadata FROM uploaded_files
WHERE uploaded_by = $1
`

func (q *Queries) FindFilesByUser(ctx context.Context, uploadedBy string) ([]UploadedFile, error) {
	rows, err := q.db.Query(ctx, findFilesByUser, uploadedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadedFile
	for rows.Next() {
		var i UploadedFile
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.FileType,
			&i.UploadedBy,
			&i.UploadedAt,
			&i.IsDeleted,
			&i.Checksum,
			&i.Description,
			&i.Provider,
			&i.ProviderMetadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findLargeSessions = `-- name: FindLargeSessions :many
SELECT id, file_size, chunk_size, max_chunk, file_name, temp_path, owner_id, current_chunk, created_at FROM sessions
WHERE file_size > $1
`

func (q *Queries) FindLargeSessions(ctx context.Context, fileSize int64) ([]Session, error) {
	rows, err := q.db.Query(ctx, findLargeSessions, fileSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.FileSize,
			&i.ChunkSize,
			&i.MaxChunk,
			&i.FileName,
			&i.TempPath,
			&i.OwnerID,
			&i.CurrentChunk,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findMissingTempPaths = `-- name: FindMissingTempPaths :many
SELECT id, file_size, chunk_size, max_chunk, file_name, temp_path, owner_id, current_chunk, created_at FROM sessions
WHERE temp_path IS NULL OR temp_path = ''
`

func (q *Queries) FindMissingTempPaths(ctx context.Context) ([]Session, error) {
	rows, err := q.db.Query(ctx, findMissingTempPaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.FileSize,
			&i.ChunkSize,
			&i.MaxChunk,
			&i.FileName,
			&i.TempPath,
			&i.OwnerID,
			&i.CurrentChunk,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSessionById = `-- name: FindSessionById :one
SELECT id, file_size, chunk_size, max_chunk, file_name, temp_path, owner_id, current_chunk, created_at FROM sessions
WHERE id = $1
`

func (q *Queries) FindSessionById(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, findSessionById, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.FileSize,
		&i.ChunkSize,
		&i.MaxChunk,
		&i.FileName,
		&i.TempPath,
		&i.OwnerID,
		&i.CurrentChunk,
		&i.CreatedAt,
	)
	return i, err
}

const findSessionsAfterDate = `-- name: FindSessionsAfterDate :many
SELECT id, file_size, chunk_size, max_chunk, file_name, temp_path, owner_id, current_chunk, created_at FROM sessions
WHERE created_at > $1
`

func (q *Queries) FindSessionsAfterDate(ctx context.Context, createdAt pgtype.Timestamp) ([]Session, error) {
	rows, err := q.db.Query(ctx, findSessionsAfterDate, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.FileSize,
			&i.ChunkSize,
			&i.MaxChunk,
			&i.FileName,
			&i.TempPath,
			&i.OwnerID,
			&i.CurrentChunk,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSessionsByDate = `-- name: FindSessionsByDate :many

SELECT id, file_size, chunk_size, max_chunk, file_name, temp_path, owner_id, current_chunk, created_at FROM sessions
WHERE DATE(created_at) = $1
`

// Requires using a slice/array in Go
func (q *Queries) FindSessionsByDate(ctx context.Context, createdAt pgtype.Timestamp) ([]Session, error) {
	rows, err := q.db.Query(ctx, findSessionsByDate, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.FileSize,
			&i.ChunkSize,
			&i.MaxChunk,
			&i.FileName,
			&i.TempPath,
			&i.OwnerID,
			&i.CurrentChunk,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSessionsByOwner = `-- name: FindSessionsByOwner :many
SELECT id, file_size, chunk_size, max_chunk, file_name, temp_path, owner_id, current_chunk, created_at FROM sessions
WHERE owner_id = $1
`

func (q *Queries) FindSessionsByOwner(ctx context.Context, ownerID pgtype.Text) ([]Session, error) {
	rows, err := q.db.Query(ctx, findSessionsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.FileSize,
			&i.ChunkSize,
			&i.MaxChunk,
			&i.FileName,
			&i.TempPath,
			&i.OwnerID,
			&i.CurrentChunk,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSessionsByOwnerIndexed = `-- name: FindSessionsByOwnerIndexed :many
SELECT id, file_size, chunk_size, max_chunk, file_name, temp_path, owner_id, current_chunk, created_at FROM sessions
WHERE owner_id = $1
`

func (q *Queries) FindSessionsByOwnerIndexed(ctx context.Context, ownerID pgtype.Text) ([]Session, error) {
	rows, err := q.db.Query(ctx, findSessionsByOwnerIndexed, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.FileSize,
			&i.ChunkSize,
			&i.MaxChunk,
			&i.FileName,
			&i.TempPath,
			&i.OwnerID,
			&i.CurrentChunk,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSessionsByOwners = `-- name: FindSessionsByOwners :many
SELECT id, file_size, chunk_size, max_chunk, file_name, temp_path, owner_id, current_chunk, created_at FROM sessions
WHERE owner_id IN ($1)
`

func (q *Queries) FindSessionsByOwners(ctx context.Context, ownerID pgtype.Text) ([]Session, error) {
	rows, err := q.db.Query(ctx, findSessionsByOwners, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.FileSize,
			&i.ChunkSize,
			&i.MaxChunk,
			&i.FileName,
			&i.TempPath,
			&i.OwnerID,
			&i.CurrentChunk,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUsersAfterDate = `-- name: FindUsersAfterDate :many
SELECT id, email, password, created_at, last_login FROM users
WHERE created_at > $1
`

func (q *Queries) FindUsersAfterDate(ctx context.Context, createdAt pgtype.Timestamp) ([]User, error) {
	rows, err := q.db.Query(ctx, findUsersAfterDate, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Password,
			&i.CreatedAt,
			&i.LastLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInactiveUsers = `-- name: GetInactiveUsers :many
SELECT id, email, password, created_at, last_login FROM users
WHERE last_login < $1
`

func (q *Queries) GetInactiveUsers(ctx context.Context, lastLogin pgtype.Timestamp) ([]User, error) {
	rows, err := q.db.Query(ctx, getInactiveUsers, lastLogin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Password,
			&i.CreatedAt,
			&i.LastLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLargestFile = `-- name: GetLargestFile :one
SELECT id, file_name, file_path, file_size, file_type, uploaded_by, uploaded_at, is_deleted, checksum, description, provider, provider_metadata FROM uploaded_files
ORDER BY file_size DESC
LIMIT 1
`

func (q *Queries) GetLargestFile(ctx context.Context) (UploadedFile, error) {
	row := q.db.QueryRow(ctx, getLargestFile)
	var i UploadedFile
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.FileType,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.IsDeleted,
		&i.Checksum,
		&i.Description,
		&i.Provider,
		&i.ProviderMetadata,
	)
	return i, err
}

const getRecentUsers = `-- name: GetRecentUsers :many
SELECT id, email, password, created_at, last_login FROM users
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) GetRecentUsers(ctx context.Context, limit int32) ([]User, error) {
	rows, err := q.db.Query(ctx, getRecentUsers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Password,
			&i.CreatedAt,
			&i.LastLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUploadedFileByID = `-- name: GetUploadedFileByID :one
SELECT id, file_name, file_path, file_size, file_type, uploaded_by, uploaded_at, is_deleted, checksum, description, provider, provider_metadata FROM uploaded_files
WHERE id = $1
`

func (q *Queries) GetUploadedFileByID(ctx context.Context, id int32) (UploadedFile, error) {
	row := q.db.QueryRow(ctx, getUploadedFileByID, id)
	var i UploadedFile
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.FileType,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.IsDeleted,
		&i.Checksum,
		&i.Description,
		&i.Provider,
		&i.ProviderMetadata,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, created_at, last_login FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password, created_at, last_login FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const hardDeleteUploadedFile = `-- name: HardDeleteUploadedFile :exec
DELETE FROM uploaded_files
WHERE id = $1
`

func (q *Queries) HardDeleteUploadedFile(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, hardDeleteUploadedFile, id)
	return err
}

const listActiveFiles = `-- name: ListActiveFiles :many
SELECT id, file_name, file_path, file_size, file_type, uploaded_by, uploaded_at, is_deleted, checksum, description, provider, provider_metadata FROM uploaded_files
WHERE is_deleted = FALSE
`

func (q *Queries) ListActiveFiles(ctx context.Context) ([]UploadedFile, error) {
	rows, err := q.db.Query(ctx, listActiveFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadedFile
	for rows.Next() {
		var i UploadedFile
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.FileType,
			&i.UploadedBy,
			&i.UploadedAt,
			&i.IsDeleted,
			&i.Checksum,
			&i.Description,
			&i.Provider,
			&i.ProviderMetadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedFiles = `-- name: ListDeletedFiles :many
SELECT id, file_name, file_path, file_size, file_type, uploaded_by, uploaded_at, is_deleted, checksum, description, provider, provider_metadata FROM uploaded_files
WHERE is_deleted = TRUE
`

func (q *Queries) ListDeletedFiles(ctx context.Context) ([]UploadedFile, error) {
	rows, err := q.db.Query(ctx, listDeletedFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadedFile
	for rows.Next() {
		var i UploadedFile
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.FileType,
			&i.UploadedBy,
			&i.UploadedAt,
			&i.IsDeleted,
			&i.Checksum,
			&i.Description,
			&i.Provider,
			&i.ProviderMetadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionDetails = `-- name: ListSessionDetails :many
SELECT id, file_name, owner_id, created_at FROM sessions
`

type ListSessionDetailsRow struct {
	ID        pgtype.UUID
	FileName  pgtype.Text
	OwnerID   pgtype.Text
	CreatedAt pgtype.Timestamp
}

func (q *Queries) ListSessionDetails(ctx context.Context) ([]ListSessionDetailsRow, error) {
	rows, err := q.db.Query(ctx, listSessionDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionDetailsRow
	for rows.Next() {
		var i ListSessionDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, file_size, chunk_size, max_chunk, file_name, temp_path, owner_id, current_chunk, created_at FROM sessions
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.FileSize,
			&i.ChunkSize,
			&i.MaxChunk,
			&i.FileName,
			&i.TempPath,
			&i.OwnerID,
			&i.CurrentChunk,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUploadedFiles = `-- name: ListUploadedFiles :many
SELECT id, file_name, file_path, file_size, file_type, uploaded_by, uploaded_at, is_deleted, checksum, description, provider, provider_metadata FROM uploaded_files
`

func (q *Queries) ListUploadedFiles(ctx context.Context) ([]UploadedFile, error) {
	rows, err := q.db.Query(ctx, listUploadedFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadedFile
	for rows.Next() {
		var i UploadedFile
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.FileType,
			&i.UploadedBy,
			&i.UploadedAt,
			&i.IsDeleted,
			&i.Checksum,
			&i.Description,
			&i.Provider,
			&i.ProviderMetadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password, created_at, last_login FROM users
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Password,
			&i.CreatedAt,
			&i.LastLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const paginateSessions = `-- name: PaginateSessions :many
SELECT id, file_size, chunk_size, max_chunk, file_name, temp_path, owner_id, current_chunk, created_at FROM sessions
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type PaginateSessionsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) PaginateSessions(ctx context.Context, arg PaginateSessionsParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, paginateSessions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.FileSize,
			&i.ChunkSize,
			&i.MaxChunk,
			&i.FileName,
			&i.TempPath,
			&i.OwnerID,
			&i.CurrentChunk,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const paginateUploadedFiles = `-- name: PaginateUploadedFiles :many
SELECT id, file_name, file_path, file_size, file_type, uploaded_by, uploaded_at, is_deleted, checksum, description, provider, provider_metadata FROM uploaded_files
WHERE is_deleted = FALSE
ORDER BY uploaded_at DESC
LIMIT $1 OFFSET $2
`

type PaginateUploadedFilesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) PaginateUploadedFiles(ctx context.Context, arg PaginateUploadedFilesParams) ([]UploadedFile, error) {
	rows, err := q.db.Query(ctx, paginateUploadedFiles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadedFile
	for rows.Next() {
		var i UploadedFile
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.FileType,
			&i.UploadedBy,
			&i.UploadedAt,
			&i.IsDeleted,
			&i.Checksum,
			&i.Description,
			&i.Provider,
			&i.ProviderMetadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const paginateUsers = `-- name: PaginateUsers :many
SELECT id, email, password, created_at, last_login FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type PaginateUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) PaginateUsers(ctx context.Context, arg PaginateUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, paginateUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Password,
			&i.CreatedAt,
			&i.LastLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProviderMetadata = `-- name: SearchProviderMetadata :many
SELECT id, file_name, file_path, file_size, file_type, uploaded_by, uploaded_at, is_deleted, checksum, description, provider, provider_metadata FROM uploaded_files
WHERE provider_metadata @> $1
`

func (q *Queries) SearchProviderMetadata(ctx context.Context, providerMetadata []byte) ([]UploadedFile, error) {
	rows, err := q.db.Query(ctx, searchProviderMetadata, providerMetadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadedFile
	for rows.Next() {
		var i UploadedFile
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.FileType,
			&i.UploadedBy,
			&i.UploadedAt,
			&i.IsDeleted,
			&i.Checksum,
			&i.Description,
			&i.Provider,
			&i.ProviderMetadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUploadedFile = `-- name: SoftDeleteUploadedFile :exec
UPDATE uploaded_files
SET is_deleted = TRUE
WHERE id = $1
`

func (q *Queries) SoftDeleteUploadedFile(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeleteUploadedFile, id)
	return err
}

const totalFileSize = `-- name: TotalFileSize :one
SELECT SUM(file_size) AS total_file_size FROM sessions
`

func (q *Queries) TotalFileSize(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, totalFileSize)
	var total_file_size int64
	err := row.Scan(&total_file_size)
	return total_file_size, err
}

const totalUploadFileSize = `-- name: TotalUploadFileSize :one
SELECT SUM(file_size) AS total_file_size FROM uploaded_files
`

func (q *Queries) TotalUploadFileSize(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, totalUploadFileSize)
	var total_file_size int64
	err := row.Scan(&total_file_size)
	return total_file_size, err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users
SET last_login = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE sessions
SET file_name = $1, temp_path = $2, current_chunk = $3
WHERE id = $4
`

type UpdateSessionParams struct {
	FileName     pgtype.Text
	TempPath     pgtype.Text
	CurrentChunk pgtype.Int8
	ID           pgtype.UUID
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.Exec(ctx, updateSession,
		arg.FileName,
		arg.TempPath,
		arg.CurrentChunk,
		arg.ID,
	)
	return err
}

const updateUploadedFileMetadata = `-- name: UpdateUploadedFileMetadata :exec
UPDATE uploaded_files
SET description = $1, provider_metadata = $2
WHERE id = $3
`

type UpdateUploadedFileMetadataParams struct {
	Description      pgtype.Text
	ProviderMetadata []byte
	ID               int32
}

func (q *Queries) UpdateUploadedFileMetadata(ctx context.Context, arg UpdateUploadedFileMetadataParams) error {
	_, err := q.db.Exec(ctx, updateUploadedFileMetadata, arg.Description, arg.ProviderMetadata, arg.ID)
	return err
}
